### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by therealabdi2** [Asad808/s3-file-monitoring#1]
looks good, just a few things to look into

we need to upload the files even if they do not match the format.

right now i think this only monitors new files, can we have it also upload files that already exists in local_folder_path?

can we update the regex to
pattern = r"^(?:\d{1,5})-(?:[1-5]|prep)-(?:[abcd]|null)-(?:math|english|urdu)$"
this way we will have exact matches only

can we also just add our aws keys (dummy keys) directly in code and not use aws cli. 
We dont want to configure aws cli on their machines.

**Comment by Asad808** [comment]
Code will first check the local folder path, if any file with the right convention (naming format) is already present in the local folder path, then the file will be uploaded. But, If the file with the wrong convention is present, then the file will never be uploaded to the bucket.

After the first step, the continuous monitoring of the directory will start, and any file with right convention, saved on the local directory will be immediately uploaded to the bucket. Any file that is already present there, will not be uploaded again.

**Comment by therealabdi2** [comment]
But we want to upload even if the file name is wrong
We can not miss any files
The text file will help us fix those wrong names later

**Comment by Asad808** [comment]
> But we want to upload even if the file name is wrong We can not miss any files The text file will help us fix those wrong names later

@therealabdi2 . I've commited some recent changes in monitor.py, accordingly.

**Comment by therealabdi2** [comment]
Thanks, can we update the regex as well

**Comment by Asad808** [comment]
> Thanks, can we update the regex as well

Updated with pattern = r"^(?:\d{1,5})-(?:[1-5]|prep)-(?:[abcd]|null)-(?:math|english|urdu)$".
